services:
  app:
    # build: . (for local build)
    # dockerhub url: https://hub.docker.com/r/imehboob/ostad-week3-docker-express/
    image: imehboob/ostad-week3-docker-express:1.1.0
    environment:
      NODE_ENV: production

  nginx:
    image: nginx:latest
    ports:
      - "8080:80" 
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
